<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PETEL_V2_Core\PETEL_V2_Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\TestCases.cs" Link="TestCases.cs" />
    <Compile Include="..\PETEL_MainTester_V2\StudentAnswer.cs" Link="StudentAnswer.cs" />
    <Compile Include="..\PETEL_MainTester_V2\TeacherAnswer.cs" Link="TeacherAnswer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
  </ItemGroup>

</Project>
